ci

diff --git a/.github/workflows/ci-konnect.yml b/.github/workflows/ci-konnect.yml
--- a/.github/workflows/ci-konnect.yml
+++ b/.github/workflows/ci-konnect.yml
@@ -26,7 +26,7 @@ jobs:
 
       # Deploy
       - name: Konnect | Deploy API Product and Publish it in the Dev Portal
-        run: |
+        run: | 
           echo -e "* Create API product 'MyHttpbin-CICD'"
           productId=$(http --ignore-stdin --raw '{"name":"MyHttpbin-CICD", "description":"A simple REST API service based on https://httpbin.apim.eu"}' POST https://$KONNECT_REGION.api.konghq.com/v2/api-products Authorization:"Bearer $KONNECT_API_TOKEN"  | jq -r '.id')
           echo 'productId='$productId
@@ -46,11 +46,19 @@ jobs:
           specificationId=$(http --ignore-stdin \
             --raw '{"name":"myhttpbin.json", "content":"'$spec'"}' \
               POST https://$KONNECT_REGION.api.konghq.com/v2/api-products/$productId/product-versions/$versionId/specifications  Authorization:"Bearer $KONNECT_API_TOKEN" | jq -r '.id')
-
           echo 'specificationId='$specificationId
+          if [ -z "$specificationId" ]; then
+            echo "Unable to push the JSON/YAML specifiation"
+            exit 1
+          fi
+
           echo -e "* Publish API product 'MyHttpbin-CICD'"
           raw='{"portal_ids": ["'$portalId'"]}'
           publicationId=$(http --ignore-stdin --raw "$raw" PATCH https://$KONNECT_REGION.api.konghq.com/v2/api-products/$productId  Authorization:"Bearer $KONNECT_API_TOKEN" | jq -r '.id')
           echo 'publicationId='$publicationId
+          if [ -z "$publicationId" ]; then
+            echo "Unable to publish the API product"
+            exit 1
+          fi
 
 
